services:
  frontend-ui:
    build:
      context: ./frontend-ui
      dockerfile: Dockerfile
    container_name: frontend-ui
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_GATEWAY_URL=http://localhost:8000
    networks:
      - app-network

  api-gateway:
    build:
      context: "./api-gateway"
      dockerfile: ./vendor/laravel/sail/runtimes/8.2/Dockerfile
      args:
        WWWGROUP: 1000
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - notification-service
    networks:
      - app-network

  auth-service:
    build:
      context: "./auth-service"
      dockerfile: ./vendor/laravel/sail/runtimes/8.2/Dockerfile
      args:
        WWWGROUP: 1001
    container_name: auth-service
    ports:
      - "8001:8001"
    environment:
      - DB_CONNECTION= mysql
      - DB_HOST= mysql-auth-service
      - DB_PORT= 3306
      - DB_DATABASE= auth_service_db
      - DB_USERNAME= sail
      - DB_PASSWORD= password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=auth_events
    depends_on:
      - rabbitmq
      - mysql-auth-service
    networks:
      - app-network

  notification-service:
    build:
      context: "./notification-service"
      dockerfile: ./vendor/laravel/sail/runtimes/8.2/Dockerfile
      args:
        WWWGROUP: 1002
    container_name: notification-service
    ports:
      - "8002:8002"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=auth_events
    depends_on:
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=sail
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - app-network

  mysql-auth-service:
    image: mysql/mysql-server:8.0
    container_name: mysql-auth-service
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_service_db
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
