services:
    auth-service:
        build:
            context: "./vendor/laravel/sail/runtimes/8.4"
            dockerfile: Dockerfile
            args:
                WWWUSER: "${WWWUSER}"
                WWWGROUP: "${WWWGROUP}"
        container_name: auth-service-sail
        image: "sail-8.4/app"
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql-auth-service
            DB_PORT: 3306
            DB_DATABASE: auth_service_db
            DB_USERNAME: sail
            DB_PASSWORD: password
            MYSQL_ROOT_HOST: "%"
        volumes:
            - ./:/var/www/html
        networks:
            - app-network

networks:
    app-network:
        external: true
        name: app-network
